### ISSUE TITLE
Maven dependency missing

### ISSUE THREAD

**Issue by christopheparisse** [Exmaralda-Org/teispeechtools#2]
Hello
I tried to compile the tools (downloaded on 17/03/2020) and maven gave me that message:
[WARNING] The POM for org.korpora.useful:utilities:jar:0.5.0 is missing, no dependency information available
and a final error message:
[ERROR] Failed to execute goal on project teispeechtools: Could not resolve dependencies for project de.ids-mannheim.clarin:teispeechtools:jar:0.7.0: Failure to find org.korpora.useful:utilities:jar:0.5.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Is there a way to download the jar file without compiling it ?
Best

**Comment by teoric** [comment]
There is a link to the utilities repository under "[Compilation](https://github.com/Exmaralda-Org/teispeechtools#Compilation)".  You just need to

    mvn install

it.  Should work with Java 8.  Otherwise, I could prepare a release.

**Comment by christopheparisse** [comment]
I have the same problem with maven install
(I tried maven package but even mvn compile does not run).

C:\brainstorm\teispeechtools>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< de.ids-mannheim.clarin:teispeechtools
>----------------
[INFO] Building teispeechtools 0.7.0
[INFO] --------------------------------[ jar
]---------------------------------
[WARNING] The POM for org.korpora.useful:utilities:jar:0.5.0 is missing, no
dependency information available
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  1.565 s
[INFO] Finished at: 2020-03-18T11:03:12+01:00
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal on project teispeechtools: Could not resolve
dependencies for project de.ids-mannheim.clarin:teispeechtools:jar:0.7.0:
Failure to find org.korpora.useful:utilities:jar:0.5.0 in
https://repo.maven.apache.org/maven2 was cached in the local repository,
resolution will not be reattempted until the update interval of central has
elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


Le mer. 18 mars 2020 à 09:43, Bernhard Fisseni <notifications@github.com> a
écrit :

**Comment by christopheparisse** [comment]
I was using java 8

**Comment by teoric** [comment]
I am not sure I understand what the problem is. May I ask you to state it more clearly?  The common procedure for installing local dependencies that are not available on a Maven repository is, as stated in the README and in the comment above, to install them locally:

    git clone git@github.com:teoric/java-utilities.git
    cd java-utilities
    mvn install

Then you can install `teispeechtools`.  Is that what you were doing?

**Comment by christopheparisse** [comment]
Hello
Yes this part is working now (would be useful to have it in the readme file).
I now have other problems:
For example:
cp@DESKTOP-82JAHDN:/mnt/c/brainstorm/teispeechtools$ java -cp 'target/dependency/*' -jar target/teispeechtools-0.7.0.jar text2iso -i ThirdPartyNoticeText.txt -o ThirdPartyNoticeText.xml
Exception in thread "main" java.lang.Error: Unresolved compilation problems:
        SimpleExmaraldaLexer cannot be resolved to a type
        SimpleExmaraldaLexer cannot be resolved to a type
        SimpleExmaralda cannot be resolved to a type
        SimpleExmaralda cannot be resolved to a type
        The method walk(ParseTreeListener, ParseTree) in the type ParseTreeWalker is not applicable for the arguments (TextToTEIConversion.TextToTEI, ParseTree)

        at de.ids.mannheim.clarin.teispeech.workflow.TextToTEIConversion.process(TextToTEIConversion.java:53)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.text2iso(CLI.java:257)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.call(CLI.java:200)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.call(CLI.java:1)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.main(CLI.java:175)

I was thinking that maybe I used the wrong command line but even with your test-text2iso.sh I have problems:
cp@DESKTOP-82JAHDN:/mnt/c/brainstorm/teispeechtools$ sh test-text2iso.sh
Exception in thread "main" java.lang.Error: Unresolved compilation problems:
        SimpleExmaraldaLexer cannot be resolved to a type
        SimpleExmaraldaLexer cannot be resolved to a type
        SimpleExmaralda cannot be resolved to a type
        SimpleExmaralda cannot be resolved to a type
        The method walk(ParseTreeListener, ParseTree) in the type ParseTreeWalker is not applicable for the arguments (TextToTEIConversion.TextToTEI, ParseTree)

        at de.ids.mannheim.clarin.teispeech.workflow.TextToTEIConversion.process(TextToTEIConversion.java:53)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.text2iso(CLI.java:257)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.call(CLI.java:200)
        at de.ids.mannheim.clarin.teispeech.tools.CLI.call(CLI.java:1)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)

Actually, none of the commands I tried did work :-( 
My main interest is to run text2iso, segmentize and pos

Thank you

**Comment by teoric** [comment]
That is annoying.  Could you write down what steps you take to compile?  I generally do:

```sh
mvn package dependency:copy-dependencies
```

What Java version are you using?

I put a ‘distribution’ (jar and dependencies) [here](https://cloud.ids-mannheim.de/s/3yXxXiAHXSdBANy) (available till 2020-04-10) for testing.  Maybe we can find out what goes wrong.

Feel free to contact me via [e-mail](mailto:fisseni@ids-mannheim.de) for further ‘playing’ till it works.
